

//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************



export class FormatCommand {
     format? : string
     source? : string
}

export class SortedDistinctListCommand {
     text? : string
}

export class FileRow {
     fileType? : FileType
     name? : string
     path? : string
     createDate? : Date
     lastModified? : Date
}

export enum FileType {
     FormatTemplate = 1,
     FixedWidthSchema = 2,
     DelimitedSchema = 3,
}

export class KeyValuePairOfstringstring {
     key? : string
     value? : string
}

export class GetAllQuery {
}

export class FormatResult {
     data? : string
     isOk? : boolean
     message? : string
     details? : KeyValuePairOfstringstring[]
}

export class GetAllResult {
     fileRows? : FileRow[]
}

export class SortedDistinctListResult {
     text? : string
     isOk? : boolean
     message? : string
     details? : KeyValuePairOfstringstring[]
}

export class WeatherForecast {
     date? : Date
     temperatureC? : number
     temperatureF? : number
     summary? : string
}

   
