using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClientGenerator
{
    public class Constants
    {
        public const string GeneratedFileDisclaimer = @"

//***************************************************************
//This code just called you a tool
//What I meant to say is that this code was generated by a tool
//so don't mess with it unless you're debugging
//subject to change without notice, might regenerate while you're reading, etc
//***************************************************************


";
        public const string GeneratedOnceFileDisclaimer = @"

//***************************************************************
//This file will not be overwritten by code generation
//Use it to override the global settings for this specific client
//***************************************************************


";
    }
}
